const GEMINI_API_KEY = process.env.GEMINI_API_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY || "dummy_gemini_key";
const MODEL_NAME = "gemini-3.1-flash-image-preview"; // Nano Banana 2

interface NanoBananaParams {
  closeupImageBase64: string;
  closeupImageMimeType: string;
  fullbodyImageBase64: string;
  fullbodyImageMimeType: string;
  garmentImageBase64: string;
  garmentImageMimeType: string;
}

export async function generateTryOnWithNanoBanana({
  closeupImageBase64,
  closeupImageMimeType,
  fullbodyImageBase64,
  fullbodyImageMimeType,
  garmentImageBase64,
  garmentImageMimeType,
}: NanoBananaParams): Promise<string> {
  if (!GEMINI_API_KEY || GEMINI_API_KEY === "dummy_gemini_key") {
    if (process.env.NODE_ENV === "production") {
      throw new Error("Missing GEMINI_API_KEY in production environment.");
    }
    console.warn("AI_API_KEY is missing or dummy. Returning mock URL.");
    return "https://via.placeholder.com/600x800?text=Try+On+Result";
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent?key=${GEMINI_API_KEY}`;

  // This prompt is improved based on the working fashion_app
  const prompt = `Virtual try-on request: I have provided a product image of a garment, a close-up selfie, and a full-body photo of a person. 
  Please render a high-fidelity image of the person from the photos wearing the exact garment. 
  Maintain the person's facial features from the selfie and body proportions from the full-body photo. 
  The resulting image should look like a professional e-commerce fashion photography asset.`;

  const payload = {
    contents: [
      {
        parts: [
          { text: prompt },
          {
            inline_data: {
              mime_type: garmentImageMimeType,
              data: garmentImageBase64,
            },
          },
          {
            inline_data: {
              mime_type: closeupImageMimeType,
              data: closeupImageBase64,
            },
          },
          {
            inline_data: {
              mime_type: fullbodyImageMimeType,
              data: fullbodyImageBase64,
            },
          },
        ],
      },
    ],
    generationConfig: {
      responseModalities: ["IMAGE"],
    },
  };

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API Error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();

    // The response for IMAGE modality returns the image data in the parts
    const candidates = data.candidates;
    if (!candidates || candidates.length === 0) {
      const errorMsg = `No image generated by Gemini (No candidates). Response: ${JSON.stringify(data)}`;
      console.error(errorMsg);
      throw new Error(errorMsg);
    }

    const parts = candidates[0].content.parts;
    const imagePart = parts.find((part: any) => part.inline_data);

    if (!imagePart) {
      const textPart = parts.find((part: any) => part.text);
      let errorMsg = "No image part found in Gemini response.";
      if (textPart) {
        errorMsg = `Gemini blocked the request or returned text: ${textPart.text}`;
      }
      errorMsg += ` Full Response: ${JSON.stringify(data)}`;
      console.error(errorMsg);
      throw new Error(errorMsg);
    }

    return imagePart.inline_data.data;
  } catch (error) {
    console.error("Error in generateTryOnWithNanoBanana:", error);
    throw error;
  }
}
